### PR TITLE
feat: Create cozy-doctypes lib ✅

### PR DESCRIPTION
**Pull request by kosssi**
fix: #7

### CODE REVIEW

**Comment by gregorylegarec** [comment]
@y-lohse I see your point but IMHO an external lib is not the obvious place either. Please convince me.

**Comment by y-lohse** [comment]
Well, every app needs a place where the doctypes constants live. Ideally it would be the same in every app for consistency's sake.
We can *probably* find such a place, even if our apps tend to have slightly different file hierarchies… but experience tells me we don't. Putting them in a dependency solves the question with no big downsides.

The minor downsides I see are

- need for updates, but realistically it won't happen very often
- package maintenance, which is automated through travis
- yet another dependency to install during dev and builds, but it's super-tiny, so 🤷‍♂️ 

If you're stil unconvinced, could you please elaborate on why you think it's a bad idea?

**Comment by CPatchane** [comment]
I am not really convinced by this idea for many reasons:

* Ok, another new dependency to add to our apps and to be aware that exists.
* Also the constants naming is wrong for me, it seems like constants we use in our apps and defined by the developer. For me if we add constants by an external library, that should be easy to use, so an object for me, and named like:
```js
export const __COZY_DOCTYPES__ = {
  ACCOUNTS : 'io.cozy.accounts',
  APPS : 'io.cozy.apps',
  BANK_ACCOUNTS : 'io.cozy.bank.accounts',
  BANK_OPERATIONS : 'io.cozy.bank.operations',
  BANK_SETTINGS : 'io.cozy.bank.settings',
  BILLS : 'io.cozy.bills',
  CONTACTS : 'io.cozy.contacts',
  FILES : 'io.cozy.files',
  NOTIFICATIONS : 'io.cozy.notifications',
  PHOTO_ALBUMS : 'io.cozy.photos.albums',
  REMOTE_REQUESTS : 'io.cozy.remote.requests'
}
```
It's better for me to use, to list (with your way, we need to go to this repo to see all doctypes available) and to avoid overwriting.
* And what about a webpack config to add? I can imagine something like `webpack.config.doctypes.js`:
```js
'use strict'

const webpack = require('webpack')

module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      __COZY_DOCTYPES__ = {
        ACCOUNTS : 'io.cozy.accounts',
        APPS : 'io.cozy.apps',
        BANK_ACCOUNTS : 'io.cozy.bank.accounts',
        BANK_OPERATIONS : 'io.cozy.bank.operations',
        BANK_SETTINGS : 'io.cozy.bank.settings',
        BILLS : 'io.cozy.bills',
        CONTACTS : 'io.cozy.contacts',
        FILES : 'io.cozy.files',
        NOTIFICATIONS : 'io.cozy.notifications',
        PHOTO_ALBUMS : 'io.cozy.photos.albums',
        REMOTE_REQUESTS : 'io.cozy.remote.requests'
      }
    })
  ]
}
```
Very easy to add to the project without adding a new dependency, easy to update and maintain (even better if we put all webpack configs in a dependency in a next future). It seems to be the best of both world here.

#my2cents

**Comment by gregorylegarec** [comment]
@y-lohse Ok for a beer :)

The main problem I see is that we are now trying to unify our apps in a single repository. So using a new external dependency seems to be counter-productive to me.

The second problem I see is that because I am used to embed the minimal amount of code,  I don't get the benefit of having somewhere in Cozy-Collect an information about the bank account doctype. For now it is only a few doctype, but what in six months, one year ? I agree that it is just a few line but if we think like this in every part of our apps we will soon have application with only 20% actually useful code. Maybe a lib structure with folders by doctype family could solve a part of this issue.

Third problem, I don't think the naming is correct here. It looks like we are rushing in a not-enough-prepared feature which will imply a huge legacy in every app. I feel that something like `BANK_SETTINGS_DOCTYPE` is not enough natural. We should implement the whole thing in a more logic way, something maybe like:
```javascript
DOCTYPES = {
  COZY: { // we may have other "doctype providers" in the future
    BANK: {
      ACCOUNTS: 'io.cozy.bank.accounts',
      OPERATIONS: 'io.cozy.bank.operations'
    }
  }
}
```
We may use it like this:
```javascript
DOCTYPE.COZY.BANK.ACCOUNT
```
and it feels more natural to me.

The more I think about this the more I feel that it is absolutely not an implementation we should rush into.

**Comment by gregorylegarec** [comment]
@CPatchane Wow I love your webpack proposition !

**Comment by enguerran** [comment]
I don't, because it couples our code with the build tool.
But I could imagine a simple js file with such constants inside.

**Comment by enguerran** [comment]
Je n'ai probablement pas compris le besoin.
On en a marre d'écrire `const FILES_DOCTYPE = 'io.cozy.files'`?
Alors, non, je ne vois vraiment pas l'intérêt.
Pourquoi ne pas écrire une lib parce qu'on en a marre d'écrire `import React from 'react'; import { connect } from 'redux';`. On pourrait avoir une lib qui permette de ne faire qu'un import `import React, { connect } from 'react-and-redux-together'`...

**Comment by kosssi** [comment]
Ok cool je voulais avoir vos avis 👍 je clos la PR et l'issue ;)

**Pull request closed without merging**
