### PR TITLE
docs: pluralize io.cozy.bank.accounts

### PR DESCRIPTION
**Pull request by gregorylegarec**

### CODE REVIEW

**Comment by gregorylegarec** [comment]
ping @m4dz

**Comment by m4dz** [comment]
Whoop, I miss this one, so sorry for the delay…

Are all doctypes pluralized into the stack? I can't figure it out…

**Comment by gregorylegarec** [comment]
@m4dz At least they have to, I am pretty sure. ping @nono

**Comment by nono** [comment]
We try to keep plural for doctypes. Not sure if it is respected at 100% tough.

**Pull request merged**
